version: '3.8'

services:
  test:
    build:
      context: src/main/java
      dockerfile: test.Dockerfile
    container_name: test
    volumes:
      - ./reports:/app/build
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - APP_NAME=customers-service
      - DB_HOST=customers_service_db
      - DB_PORT=5432
      - DB_NAME=customers_service
      - DB_USER=customers_service
      - DB_PASSWORD=customers_service
    depends_on:
      - db
    command: >
      ./gradlew --no-daemon
      -g ./.gradle-cache
      test
  db:
    image: postgres:latest
    container_name: customers_service_db
    environment:
      POSTGRES_DB: customers_service_db
      POSTGRES_USER: customers_service
      POSTGRES_PASSWORD: customers_service